pins:
  sda: 3
  scl: 5
  mld: 11
  uce: 12
  ms:  13
  mrd: 15
  uct: 16
  ure: 18
  urt: 22
  ela: 23
  era: 24
  erb: 26
  elb: 19
  lg:  31
  lr:  29
  mlp: 32
  mrp: 33
  ult: 35
  ule: 37
ip_addresses:
  lagann: "192.168.1.1"
  blinky: "192.168.1.2"
  inky:   "192.168.1.3"
  clyde:  "192.168.1.4"
  t430:   "192.168.1.5"
ticks_meter: 6530
base_width: 0.141
enc_rate: 50
us_rate: 5
us_angle: deg(30)
us_time: 0.05
imu_rate: 50
pid:
  Kp: 0.176
  Ki: 0
  Kd: 0.008
